import React, { useEffect } from "react";
import Layout from "../components/Layout";
import MusicCardSimple from "../components/MusicCardSimple";
import { Track } from "../types/audio";
import { usePlayer } from "../contexts/PlayerContext";

const homeContent: Track[] = [
  {
    id: "1",
    title: "bad guy",
    artist: "Billie Eilish",
    genre: "Pop",
    mood: "Energetic",
    duration: "3:14",
    url: "/audio/bad-guy.mp3",
    coverArt: "/images/bad-guy-cover.jpg",
    bpm: 135,
  },
  {
    id: "2",
    title: "Happier Than Ever",
    artist: "Billie Eilish",
    genre: "Pop-Rock",
    mood: "Melancholic",
    duration: "4:58",
    url: "/audio/happier-than-ever.mp3",
    coverArt: "/images/happier-than-ever-cover.jpg",
    bpm: 81,
  },
  {
    id: "3",
    title: "Therefore I Am",
    artist: "Billie Eilish",
    genre: "Alternative",
    mood: "Confident",
    duration: "2:54",
    url: "/audio/therefore-i-am.mp3",
    coverArt: "/images/therefore-i-am-cover.jpg",
    bpm: 94,
  },
  {
    id: "4",
    title: "ocean eyes",
    artist: "Billie Eilish",
    genre: "Indie Pop",
    mood: "Dreamy",
    duration: "3:20",
    url: "/audio/ocean-eyes.mp3",
    coverArt: "/images/ocean-eyes-cover.jpg",
    bpm: 73,
  },
  {
    id: "5",
    title: "when the party's over",
    artist: "Billie Eilish",
    genre: "Ballad",
    mood: "Sad",
    duration: "3:16",
    url: "/audio/when-the-partys-over.mp3",
    coverArt: "/images/when-the-partys-over-cover.jpg",
    bpm: 62,
  },
  {
    id: "6",
    title: "What Was I Made For?",
    artist: "Billie Eilish",
    genre: "Ballad",
    mood: "Introspective",
    duration: "3:42",
    url: "/audio/what-was-i-made-for.mp3",
    coverArt: "/images/what-was-i-made-for-cover.jpg",
    bpm: 78,
  },
  {
    id: "7",
    title: "bury a friend",
    artist: "Billie Eilish",
    genre: "Dark Pop",
    mood: "Eerie",
    duration: "3:13",
    url: "/audio/bury-a-friend.mp3",
    coverArt: "/images/bury-a-friend-cover.jpg",
    bpm: 120,
  },
  {
    id: "8",
    title: "No Time To Die",
    artist: "Billie Eilish",
    genre: "Orchestral Pop",
    mood: "Dramatic",
    duration: "4:02",
    url: "/audio/no-time-to-die.mp3",
    coverArt: "/images/no-time-to-die-cover.jpg",
    bpm: 75,
  },
  {
    id: "9",
    title: "everything i wanted",
    artist: "Billie Eilish",
    genre: "Pop",
    mood: "Reflective",
    duration: "4:05",
    url: "/audio/everything-i-wanted.mp3",
    coverArt: "/images/everything-i-wanted-cover.jpg",
    bpm: 120,
  },
  {
    id: "10",
    title: "lovely",
    artist: "Billie Eilish",
    genre: "Indie Pop",
    mood: "Emotional",
    duration: "3:20",
    url: "/audio/lovely.mp3",
    coverArt: "/images/lovely-cover.jpg",
    bpm: 115,
  },
  {
    id: "11",
    title: "LUNCH",
    artist: "Billie Eilish",
    genre: "Pop",
    mood: "Flirty",
    duration: "2:59",
    url: "/audio/lunch.mp3",
    coverArt: "/images/lunch-cover.jpg",
    bpm: 125,
  },
  {
    id: "12",
    title: "L'AMOUR DE MA VIE",
    artist: "Billie Eilish",
    genre: "Synth-Pop",
    mood: "Rebellious",
    duration: "5:33",
    url: "/audio/lamour-de-ma-vie.mp3",
    coverArt: "/images/lamour-de-ma-vie-cover.jpg",
    bpm: 125,
  },
  {
    id: "13",
    title: "Chihiro",
    artist: "Billie Eilish",
    genre: "Alternative",
    mood: "Mysterious",
    duration: "4:12",
    url: "/audio/chihiro.mp3",
    coverArt: "/images/chihiro-cover.jpg",
    bpm: 110,
  },
  {
    id: "14",
    title: "Birds of a Feather",
    artist: "Billie Eilish",
    genre: "Pop",
    mood: "Upbeat",
    duration: "3:30",
    url: "/audio/birds-of-a-feather.mp3",
    coverArt: "/images/birds-of-a-feather-cover.jpg",
    bpm: 105,
  },
  {
    id: "15",
    title: "Wildflower",
    artist: "Billie Eilish",
    genre: "Indie Folk",
    mood: "Gentle",
    duration: "4:21",
    url: "/audio/wildflower.mp3",
    coverArt: "/images/wildflower-cover.jpg",
    bpm: 90,
  },
  {
    id: "16",
    title: "The Greatest",
    artist: "Billie Eilish",
    genre: "Ballad",
    mood: "Powerful",
    duration: "4:53",
    url: "/audio/the-greatest.mp3",
    coverArt: "/images/the-greatest-cover.jpg",
    bpm: 70,
  },
  {
    id: "17",
    title: "The Diner",
    artist: "Billie Eilish",
    genre: "Alternative",
    mood: "Dark",
    duration: "3:06",
    url: "/audio/the-diner.mp3",
    coverArt: "/images/the-diner-cover.jpg",
    bpm: 140,
  },
  {
    id: "18",
    title: "Bittersuite",
    artist: "Billie Eilish",
    genre: "Electronic",
    mood: "Intense",
    duration: "4:58",
    url: "/audio/bittersuite.mp3",
    coverArt: "/images/bittersuite-cover.jpg",
    bpm: 128,
  },
  {
    id: "19",
    title: "Blue",
    artist: "Billie Eilish",
    genre: "Pop",
    mood: "Sad",
    duration: "5:43",
    url: "/audio/blue.mp3",
    coverArt: "/images/blue-cover.jpg",
    bpm: 85,
  },
  {
    id: "20",
    title: "Getting Older",
    artist: "Billie Eilish",
    genre: "Pop",
    mood: "Reflective",
    duration: "4:04",
    url: "/audio/getting-older.mp3",
    coverArt: "/images/getting-older-cover.jpg",
    bpm: 100,
  },
  {
    id: "21",
    title: "I Didn't Change My Number",
    artist: "Billie Eilish",
    genre: "Alternative",
    mood: "Confident",
    duration: "2:38",
    url: "/audio/i-didnt-change-my-number.mp3",
    coverArt: "/images/i-didnt-change-my-number-cover.jpg",
    bpm: 125,
  },
  {
    id: "22",
    title: "Billie Bossa Nova",
    artist: "Billie Eilish",
    genre: "Bossa Nova",
    mood: "Sensual",
    duration: "3:16",
    url: "/audio/billie-bossa-nova.mp3",
    coverArt: "/images/billie-bossa-nova-cover.jpg",
    bpm: 100,
  },
  {
    id: "23",
    title: "My Future",
    artist: "Billie Eilish",
    genre: "R&B",
    mood: "Hopeful",
    duration: "3:30",
    url: "/audio/my-future.mp3",
    coverArt: "/images/my-future-cover.jpg",
    bpm: 90,
  },
  {
    id: "24",
    title: "Oxytocin",
    artist: "Billie Eilish",
    genre: "Electronic",
    mood: "Energetic",
    duration: "3:30",
    url: "/audio/oxytocin.mp3",
    coverArt: "/images/oxytocin-cover.jpg",
    bpm: 125,
  },
  {
    id: "25",
    title: "Goldwing",
    artist: "Billie Eilish",
    genre: "Alternative",
    mood: "Ethereal",
    duration: "2:31",
    url: "/audio/goldwing.mp3",
    coverArt: "/images/goldwing-cover.jpg",
    bpm: 80,
  },
  {
    id: "26",
    title: "Lost Cause",
    artist: "Billie Eilish",
    genre: "Pop",
    mood: "Chill",
    duration: "3:32",
    url: "/audio/lost-cause.mp3",
    coverArt: "/images/lost-cause-cover.jpg",
    bpm: 100,
  },
  {
    id: "27",
    title: "Halley's Comet",
    artist: "Billie Eilish",
    genre: "Ballad",
    mood: "Romantic",
    duration: "3:54",
    url: "/audio/halleys-comet.mp3",
    coverArt: "/images/halleys-comet-cover.jpg",
    bpm: 70,
  },
  {
    id: "28",
    title: "Not My Responsibility",
    artist: "Billie Eilish",
    genre: "Spoken Word",
    mood: "Serious",
    duration: "3:47",
    url: "/audio/not-my-responsibility.mp3",
    coverArt: "/images/not-my-responsibility-cover.jpg",
    bpm: 120,
  },
  {
    id: "29",
    title: "Overheated",
    artist: "Billie Eilish",
    genre: "Alternative",
    mood: "Tense",
    duration: "3:34",
    url: "/audio/overheated.mp3",
    coverArt: "/images/overheated-cover.jpg",
    bpm: 120,
  },
  {
    id: "30",
    title: "Everybody Dies",
    artist: "Billie Eilish",
    genre: "Ballad",
    mood: "Melancholic",
    duration: "3:26",
    url: "/audio/everybody-dies.mp3",
    coverArt: "/images/everybody-dies-cover.jpg",
    bpm: 80,
  },
  {
    id: "31",
    title: "Your Power",
    artist: "Billie Eilish",
    genre: "Folk",
    mood: "Serious",
    duration: "4:05",
    url: "/audio/your-power.mp3",
    coverArt: "/images/your-power-cover.jpg",
    bpm: 90,
  },
  {
    id: "32",
    title: "NDA",
    artist: "Billie Eilish",
    genre: "Alternative",
    mood: "Dark",
    duration: "3:15",
    url: "/audio/nda.mp3",
    coverArt: "/images/nda-cover.jpg",
    bpm: 130,
  },
];

const Home = () => {
  const { setPlaylist } = usePlayer();

  useEffect(() => {
    // Set the playlist when the component mounts
    setPlaylist(homeContent);
  }, [setPlaylist]);

  return (
    <Layout title="Home">
      <section className="mb-8">
        <h1>Welcome to Audio4lab</h1>
        <h2 className="text-5xl font-bold mt-3 text-white">
        Embark on a creative journey
        </h2>
        <h2 className="text-2xl font-bold mb-6 mt-20 text-white">
        Explore music to match your project
        </h2>
        <div className="flex flex-wrap gap-4 lg:gap-6 justify-center md:justify-start">
          {homeContent.map((track) => (
            <MusicCardSimple
              key={track.id}
              track={track}
              showDownload={true}
              showPlayButton={true}
            />
          ))}
        </div>
      </section>
    </Layout>
  );
};

export default Home;